import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'match' },
  { path: 'about', loadComponent: () => import('./pages/about/about').then((m) => m.About) },
  { path: 'login', loadComponent: () => import('./pages/login/login.page').then((m) => m.LoginPage) },
  { path: 'forgot-password', loadComponent: () => import('./pages/forgot-password/forgot-password.page').then((m) => m.ForgotPasswordPage) },
  { path: 'register', loadComponent: () => import('./pages/register/register.page').then((m) => m.RegisterPage) },
  { path: 'verify-email', loadComponent: () => import('./pages/verify-email/verify-email.page').then((m) => m.VerifyEmailPage) },
  { path: 'profile', loadComponent: () => import('./pages/profile/profile.page').then((m) => m.ProfilePage) },
  { path: 'profile/saved-apartments', loadComponent: () => import('./pages/saved-apartments/saved-apartments.page').then((m) => m.SavedApartmentsPage) },
  { path: 'profile/calculation-history', loadComponent: () => import('./pages/calculation-history/calculation-history.page').then((m) => m.CalculationHistoryPage) },
  { path: 'profile/my-listings', loadComponent: () => import('./pages/my-listings/my-listings.page').then((m) => m.MyListingsPage) },
  { path: 'ai-consultant', loadComponent: () => import('./pages/ai-consultant/ai-consultant.page').then((m) => m.AIConsultantPage) },
  { path: 'match', loadComponent: () => import('./pages/mortgage-match/mortgage-match.page').then((m) => m.MortgageMatchPage) },
  { path: 'programs', loadComponent: () => import('./pages/programs-list/programs-list.page').then((m) => m.ProgramsListPage) },
  { path: 'programs/:id', loadComponent: () => import('./pages/program-detail/program-detail.page').then((m) => m.ProgramDetailPage) },
  { path: 'banks', loadComponent: () => import('./pages/banks-list/banks-list.page').then((m) => m.BanksListPage) },
  { path: 'banks/:id', loadComponent: () => import('./pages/bank-detail/bank-detail.page').then((m) => m.BankDetailPage) },
  { path: 'news', loadComponent: () => import('./pages/news/news.page').then((m) => m.NewsPage) },
  { path: 'news/:id', loadComponent: () => import('./pages/news-detail/news-detail.page').then((m) => m.NewsDetailPage) },
  { path: 'estate/primary', loadComponent: () => import('./pages/estate-primary/estate-primary.page').then((m) => m.EstatePrimaryPage) },
  { path: 'estate/secondary', loadComponent: () => import('./pages/estate-secondary/estate-secondary.page').then((m) => m.EstateSecondaryPage) },
  { path: 'estate/apartment/:id', loadComponent: () => import('./pages/apartment-detail/apartment-detail.page').then((m) => m.ApartmentDetailPage) },
  { path: 'estate/submit', loadComponent: () => import('./pages/submit-ad/submit-ad.page').then((m) => m.SubmitAdPage) },
];
